management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
        - "*"

  endpoint:
    shutdown:
      enabled: true

description :  Spring Boot Rest With OpenAPI-v3

      
version: OpenAPI-v3

# Application name
spring:
  application:
    name: RestfulAPI

# Logging level
logging:
  level:
    root: INFO

# Logstash appender
logstash:
  destination: localhost:5000


